const images = {
  loginLogo: require('./images/logo-circle.png'),
  bg: require('./images/bg.png'),
  icon: {
    facebook: require('./images/icon/facebook.png'),
    twitter: require('./images/icon/twitter.png'),
    instagram: require('./images/icon/instagram.png'),
    google: require('./images/icon/google.png'),
    mars: require('./images/icon/mars.png'),
    venus: require('./images/icon/venus.png'),
    back: require('./images/icon/back.png'),
    profile: require('./images/icon/profile.png'),
    find: require('./images/icon/find.png'),
    message: require('./images/icon/conversation.png'),
    pet: require('./images/icon/animal-paw.png'),
    pawOutline: require('./images/icon/animal-paw-outline.png'),
    locationPin: require('./images/icon/pin.png'),
    navigation: require('./images/icon/navigation.png'),
    locationCirclePin: require('./images/icon/circle-map-pin.png'),
  },
  defaultAvatar: require('./images/default-avatar.png'),
  petDefaultAvatar: require('./images/pet-default-avatar.png'),
  dog1: require('./images/dog1.png'),
  dog2: require('./images/dog2.jpg'),
  dog3: require('./images/dog3.jpg'),
  dog4: require('./images/dog4.jpg'),
  story: require('./images/story.png'),
  homeActive: require('./images/home_active.png'),
  petActive: require('./images/pet_active.png'),
  placeActive: require('./images/place_active.png'),
  messageActive: require('./images/message_active.png'),
};

export default images;
