export const locationConstants = {
  
  SEARCH_LOCATION_REQUEST : "SEARCH_LOCATION_REQUEST",
  SEARCH_LOCATION_SUCCESS : "SEARCH_LOCATION_SUCCESS",
  SEARCH_LOCATION_FAILURE : "SEARCH_LOCATION_FAILURE",

  LOCATION_DETAILS_REQUEST : "LOCATION_DETAILS_REQUEST",
  LOCATION_DETAILS_SUCCESS : "LOCATION_DETAILS_SUCCESS",
  LOCATION_DETAILS_FAILURE : "LOCATION_DETAILS_FAILURE",

  UPDATE_CURRENT_LOCATION_REQUEST : "UPDATE_CURRENT_LOCATION_REQUEST",
  UPDATE_CURRENT_LOCATION_SUCCESS : "UPDATE_CURRENT_LOCATION_SUCCESS",
  UPDATE_CURRENT_LOCATION_FAILURE : "UPDATE_CURRENT_LOCATION_FAILURE",

  GET_USERS_AROUND_REQUEST : "GET_USERS_AROUND_REQUEST",
  GET_USERS_AROUND_SUCCESS : "GET_USERS_AROUND_SUCCESS",
  GET_USERS_AROUND_FAILURE : "GET_USERS_AROUND_FAILURE",
};
