export const messageConstants = {
  
    SEND_MESSAGE_REQUEST : "SEND_MESSAGE_REQUEST",
    SEND_MESSAGE_SUCCESS : "SEND_MESSAGE_SUCCESS",
    SEND_MESSAGE_FAILURE : "SEND_MESSAGE_FAILURE",

    VIEW_INBOX_REQUEST : "VIEW_INBOX_REQUEST",
    VIEW_INBOX_SUCCESS : "VIEW_INBOX_SUCCESS",
    VIEW_INBOX_FAILURE : "VIEW_INBOX_FAILURE",

    VIEW_THREAD_REQUEST : "VIEW_THREAD_REQUEST",
    VIEW_THREAD_SUCCESS : "VIEW_THREAD_SUCCESS",
    VIEW_THREAD_FAILURE : "VIEW_THREAD_FAILURE",
    
    SET_MESSAGE_BADGE : "SET_MESSAGE_BADGE"

  };
  