export const petConstants = {
  
    UPDATE_PET_REQUEST : "UPDATE_PET_REQUEST",
    UPDATE_PET_SUCCESS : "UPDATE_PET_SUCCESS",
    UPDATE_PET_FAILURE : "UPDATE_PET_FAILURE",

    PET_PHOTO_REQUEST : "PET_PHOTO_REQUEST",
    PET_PHOTO_SUCCESS : "PET_PHOTO_SUCCESS",
    PET_PHOTO_FAILURE : "PET_PHOTO_FAILURE",

    OWNER_PET_PHOTO_REQUEST : "OWNER_PET_PHOTO_REQUEST",
    OWNER_PET_PHOTO_SUCCESS : "OWNER_PET_PHOTO_SUCCESS",
    OWNER_PET_PHOTO_FAILURE : "OWNER_PET_PHOTO_FAILURE",

    UPLOAD_PET_PHOTO_REQUEST : "UPLOAD_PET_PHOTO_REQUEST",
    UPLOAD_PET_PHOTO_SUCCESS : "UPLOAD_PET_PHOTO_SUCCESS",
    UPLOAD_PET_PHOTO_FAILURE : "UPLOAD_PET_PHOTO_FAILURE",
  };
  