export const userConstants = {
    LOGIN_REQUEST : "LOGIN_REQUEST",
    LOGIN_SUCCESS : "LOGIN_SUCCESS",
    LOGIN_FAILURE : "LOGIN_FAILURE",
    LOGOUT : "LOGOUT",
    setInit : "setInit",
    
    SOCIAL_LOGIN_SUCCESS: "SOCIAL_LOGIN_SUCCESS",

    USER_PETS_REQUEST : "USER_PETS_REQUEST",
    USER_PETS_SUCCESS : "USER_PETS_SUCCESS",
    USER_PETS_FAILURE : "USER_PETS_FAILURE",

    USER_PETS_PHOTO_REQUEST : "USER_PETS_PHOTO_REQUEST",
    USER_PETS_PHOTO_SUCCESS : "USER_PETS_PHOTO_SUCCESS",
    USER_PETS_PHOTO_FAILURE : "USER_PETS_PHOTO_FAILURE",

    OWNER_PETS_REQUEST : "OWNER_PETS_REQUEST",
    OWNER_PETS_SUCCESS : "OWNER_PETS_SUCCESS",
    OWNER_PETS_FAILURE : "OWNER_PETS_FAILURE",

    OWNER_PETS_PHOTO_REQUEST : "OWNER_PETS_PHOTO_REQUEST",
    OWNER_PETS_PHOTO_SUCCESS : "OWNER_PETS_PHOTO_SUCCESS",
    OWNER_PETS_PHOTO_FAILURE : "OWNER_PETS_PHOTO_FAILURE",

    OWNER_REQUEST : "OWNER_REQUEST",
    OWNER_SUCCESS : "OWNER_SUCCESS",
    OWNER_FAILURE : "OWNER_FAILURE",

    SET_DEVICES : "SET_DEVICES",

  };
  